### ISSUE TITLE
Docs do not reflect 9.5 support

### ISSUE THREAD

**Issue by jfinzel** [reorg/pg_repack#88]
[This issue](https://github.com/reorg/pg_repack/issues/67) seems to reflect that 9.5 is supported in 1.3.3, however this is confusing because the documentation available only points to 1.3.1: http://reorg.github.io/pg_repack/

Here is does not say 9.5 is supported.  Can docs be updated here?

**Comment by schmiddy** [comment]
Yeah, this is my fault for not pushing documentation updates with the last few releases. @dvarrazzo I run into complaints like this when I try to run `make` per the "Upload the docs" [section of the instructions](https://github.com/reorg/pg_repack/blob/master/doc/release.rst):
```
$ make
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: class Writer has no attribute 'default_stylesheet_path'
mkdir -p pg_repack/1.3/
python tools/addversion.py 1.3.1 < sm/1.3/doc/pg_repack.rst | /usr/bin/rst2html --template=template.txt --stylesheet-path=sm/master/doc/style.css, --initial-header-level=2 > pg_repack/1.3/index.html
cat pg_repack/1.3/index.html > pg_repack/index.html
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: class Writer has no attribute 'default_stylesheet_path'
mkdir -p pg_repack/1.1/
python tools/addversion.py 1.1.8 < sm/1.1/doc/pg_repack.rst | /usr/bin/rst2html --template=template.txt --stylesheet-path=sm/master/doc/style.css, --initial-header-level=2 > pg_repack/1.1/index.html
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: class Writer has no attribute 'default_stylesheet_path'
mkdir -p pg_repack/1.2/
python tools/addversion.py 1.2.1 < sm/1.2/doc/pg_repack.rst | /usr/bin/rst2html --template=template.txt --stylesheet-path=sm/master/doc/style.css, --initial-header-level=2 > pg_repack/1.2/index.html
```

BTW those version numbers fed to `addversion.py` are supposed to get updated automatically right? Any idea why that's not happening, i.e. why `1.3.1` is still being used?

**Comment by blakeday** [comment]
While we're at it, do we know if 9.6 is supported?

**Comment by MasahikoSawada** [comment]
I can not find out cause of this error yet but ISTM that rst2html.py command is done successfully if I do that command manually. And the result html file (index.html) is created properly even if that error happen.

```bash
$ make
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: class Writer has no attribute 'default_stylesheet_path'
mkdir -p pg_repack/1.3/
python tools/addversion.py 1.3.1 < sm/1.3/doc/pg_repack.rst | /usr/bin/rst2html.py --template=template.txt --stylesheet-path=sm/master/doc/style.css, --initial-header-level=2 > pg_repack/1.3/index.html
cat pg_repack/1.3/index.html > pg_repack/index.html
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: class Writer has no attribute 'default_stylesheet_path'
mkdir -p pg_repack/1.1/
python tools/addversion.py 1.1.8 < sm/1.1/doc/pg_repack.rst | /usr/bin/rst2html.py --template=template.txt --stylesheet-path=sm/master/doc/style.css, --initial-header-level=2 > pg_repack/1.1/index.html
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: class Writer has no attribute 'default_stylesheet_path'
mkdir -p pg_repack/1.2/
python tools/addversion.py 1.2.1 < sm/1.2/doc/pg_repack.rst | /usr/bin/rst2html.py --template=template.txt --stylesheet-path=sm/master/doc/style.css, --initial-header-level=2 > pg_repack/1.2/index.html
$ python tools/addversion.py 1.1.8 < sm/1.1/doc/pg_repack.rst | /usr/bin/rst2html.py --template=template.txt --stylesheet-path=sm/master/doc/style.css, --initial-header-level=2 > /tmp/index.html
$ /usr/bin/diff -q /tmp/index.html pg_repack/1.1/index.html
$
```

> BTW those version numbers fed to addversion.py are supposed to get updated automatically right? Any idea why that's not happening, i.e. why 1.3.1 is still being used?

It depend on `git submodule` rather than `addversion.py`. Current commit reference is the following. We should update them.

```bash
$ git submodule
 4ea1673472701f592ac0b03ebe0e8d2047c9013d sm/1.1 (ver_1.1.8)
 a9f3682645e5181b342fe5f113b77d85b7515e59 sm/1.2 (ver_1.2.1)
 f4703be524b74e8c513687e6ed7991d58feaf559 sm/master (ver_1.3.1)
```

**Comment by dvarrazzo** [comment]
I have updated the submodules and the docs and regenerated.

@schmiddy error was probably caused by an old unsupported rst2html version: the Makefile now installs a local one so it should work consistently.
